export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  paradoxApiKey: process.env.PARADOX_API_KEY ?? "",
  paradoxPassphrase: process.env.PARADOX_PASSPHRASE ?? "",
  paradoxGatewayUrl: process.env.PARADOX_GATEWAY_URL ?? "https://paradoxdb.onrender.com/v1",
  paradoxProjectName: process.env.PARADOX_PROJECT_NAME ?? "nexuss-agent",
  paradoxDatabaseName: process.env.PARADOX_DATABASE_NAME ?? "nexuss-agent",
  nexussAuthUrl: process.env.NEXUSS_AUTH_URL ?? "https://nexuss-auth.vercel.app",
  nexussAuthProjectId: process.env.NEXUSS_AUTH_PROJECT_ID ?? "nexuss-agent-v2",
  nexussAuthRedirectUri: process.env.NEXUSS_AUTH_REDIRECT_URI ?? "https://nexuss-agents.onrender.com/auth/callback",
};
