export type SkillId = "mission_planning" | "mission_decomposition" | "specialist_selection" | "repository_inspection" | "bounded_execution" | "failure_classification" | "quality_verification" | "skill_selection" | "research" | "browser" | "webdev" | "terminal";
export type SkillStatus = "implemented" | "contract_only";
export type SkillDescriptor = { id: SkillId; version: string; title: string; status: SkillStatus; purpose: string; inputs: readonly string[]; outputs: readonly string[]; requiredHarnesses: readonly string[]; sideEffect: "none" | "bounded_repository_write" | "external_read" | "external_write"; verification: readonly string[] };

const skills: Record<SkillId, SkillDescriptor> = {
  mission_planning: { id: "mission_planning", version: "1.0.0", title: "Mission Planning", status: "implemented", purpose: "Normalize a mission into bounded work with acceptance criteria and dependencies.", inputs: ["mission contract", "repository context"], outputs: ["validated work graph", "assumptions"], requiredHarnesses: ["mission_runtime"], sideEffect: "none", verification: ["schema validation", "dependency validation"] },
  mission_decomposition: { id: "mission_decomposition", version: "1.0.0", title: "Mission Decomposition", status: "implemented", purpose: "Split a bounded objective into independently verifiable work.", inputs: ["bounded objective", "budget"], outputs: ["child work specifications"], requiredHarnesses: ["mission_runtime"], sideEffect: "none", verification: ["budget check", "dependency check"] },
  specialist_selection: { id: "specialist_selection", version: "1.0.0", title: "Specialist Selection", status: "implemented", purpose: "Select registered agents whose authority matches a work item.", inputs: ["work item", "role registry"], outputs: ["specialist assignment"], requiredHarnesses: ["specialist_spawn"], sideEffect: "none", verification: ["capability check"] },
  repository_inspection: { id: "repository_inspection", version: "1.0.0", title: "Repository Inspection", status: "implemented", purpose: "Inspect repository state through bounded read-only operations.", inputs: ["repository root"], outputs: ["status", "tracked files", "bounded metadata"], requiredHarnesses: ["repository_inspection"], sideEffect: "none", verification: ["path confinement", "bounded output"] },
  bounded_execution: { id: "bounded_execution", version: "1.0.0", title: "Bounded Repository Execution", status: "implemented", purpose: "Apply constrained complete-file changes and allowlisted verification commands.", inputs: ["validated write operations", "allowlisted commands"], outputs: ["changed paths", "command results"], requiredHarnesses: ["repository_change", "repository_verification"], sideEffect: "bounded_repository_write", verification: ["path policy", "command policy", "quality gate"] },
  failure_classification: { id: "failure_classification", version: "1.0.0", title: "Failure Classification", status: "implemented", purpose: "Classify failures as retryable, repairable, blocked, cancelled, or terminal.", inputs: ["bounded result", "mission policy"], outputs: ["failure class", "next action"], requiredHarnesses: ["mission_runtime"], sideEffect: "none", verification: ["allowed classification"] },
  quality_verification: { id: "quality_verification", version: "1.0.0", title: "Independent Quality Verification", status: "implemented", purpose: "Run independent type, test, build, and diff checks without writing files.", inputs: ["repository state", "acceptance criteria"], outputs: ["quality result", "evidence summaries"], requiredHarnesses: ["repository_verification"], sideEffect: "none", verification: ["exit status", "bounded output"] },
  skill_selection: { id: "skill_selection", version: "1.0.0", title: "Skill Selection", status: "implemented", purpose: "Choose skills that match a mission without treating them as architectural modes.", inputs: ["mission objective", "skill registry"], outputs: ["skill assignments"], requiredHarnesses: ["mission_runtime"], sideEffect: "none", verification: ["registry lookup"] },
  research: { id: "research", version: "1.0.0", title: "Research", status: "contract_only", purpose: "Gather and synthesize external information when a mission requires it.", inputs: ["research question", "source policy"], outputs: ["source-backed findings"], requiredHarnesses: ["research"], sideEffect: "external_read", verification: ["source provenance", "citation checks"] },
  browser: { id: "browser", version: "1.0.0", title: "Browser Interaction", status: "contract_only", purpose: "Observe or interact with web pages through a guarded browser capability.", inputs: ["navigation target", "interaction request"], outputs: ["observed state", "artifact reference"], requiredHarnesses: ["browser"], sideEffect: "external_read", verification: ["page-state evidence", "authorization boundary"] },
  webdev: { id: "webdev", version: "1.0.0", title: "WebDev Delivery", status: "contract_only", purpose: "Build or deploy a web application through an approved project/deployment capability.", inputs: ["application change", "deployment policy"], outputs: ["build result", "deployment evidence"], requiredHarnesses: ["webdev"], sideEffect: "external_write", verification: ["build checks", "deployment checks"] },
  terminal: { id: "terminal", version: "1.0.0", title: "Terminal Operations", status: "contract_only", purpose: "Perform terminal actions only through an explicit future terminal policy.", inputs: ["bounded command request"], outputs: ["command result"], requiredHarnesses: ["terminal"], sideEffect: "bounded_repository_write", verification: ["command allowlist", "timeout", "output bound"] },
};

export function getSkill(id: SkillId) { return skills[id]; }
export function listSkills() { return Object.values(skills); }
export function isSkillImplemented(id: SkillId) { return skills[id].status === "implemented"; }
