import { Activity, GitCommitHorizontal, GitPullRequest, RefreshCw, Star, Users, Workflow, X } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Repo = { fullName: string; defaultBranch: string };
type Analytics = { repository: { stars: number; forks: number; openIssues: number; language: string | null; pushedAt: string | null }; commits: Array<{ sha: string | null; message: string; author: string; date: string | null }>; pulls: Array<{ number: number; state: string; merged: boolean; draft: boolean }>; contributors: Array<{ login: string; contributions: number }>; workflow: { total: number; successful: number; completed: number; successRate: number | null } };

function Metric({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <div className="nexuss-git-analytics-metric"><span>{icon}</span><small>{label}</small><strong>{value}</strong><em>{detail}</em></div>; }

export default function NexussGitAnalyticsPanel({ repository }: { repository: Repo | null }) {
  const query = trpc.workspace.github.analytics.useQuery({ fullName: repository?.fullName || "placeholder/repository" }, { enabled: Boolean(repository), retry: false, staleTime: 60_000 });
  if (!repository) return <div className="nexuss-git-search-placeholder"><Activity size={18} /> Choose a repository to view developer activity metrics.</div>;
  if (query.isLoading) return <div className="nexuss-git-search-placeholder"><RefreshCw size={17} className="nexuss-git-spin" /> Aggregating repository activity…</div>;
  if (query.isError) return <div className="nexuss-git-search-placeholder nexuss-git-file-error"><X size={17} /> Analytics could not be loaded.<button type="button" onClick={() => void query.refetch()}>Retry</button></div>;
  const data = query.data as Analytics | undefined;
  if (!data) return null;
  const merged = data.pulls.filter((pull) => pull.merged).length; const open = data.pulls.filter((pull) => pull.state === "open").length;
  return <div className="nexuss-git-analytics-workspace"><div className="nexuss-git-file-toolbar"><div><span className="nexuss-git-eyebrow">{repository.fullName}</span><strong>Repository analytics</strong></div><button type="button" className="nexuss-git-icon-button" onClick={() => void query.refetch()} aria-label="Refresh analytics"><RefreshCw size={13} /></button></div><div className="nexuss-git-analytics-grid"><Metric icon={<GitCommitHorizontal size={14} />} label="Recent commits" value={String(data.commits.length)} detail="latest sample" /><Metric icon={<GitPullRequest size={14} />} label="Pull requests" value={String(data.pulls.length)} detail={`${open} open · ${merged} merged`} /><Metric icon={<Workflow size={14} />} label="Workflow health" value={data.workflow.successRate === null ? "—" : `${data.workflow.successRate}%`} detail={`${data.workflow.successful}/${data.workflow.completed} successful`} /><Metric icon={<Users size={14} />} label="Contributors" value={String(data.contributors.length)} detail="recent contributors" /><Metric icon={<Star size={14} />} label="Stars" value={String(data.repository.stars)} detail={`${data.repository.forks} forks`} /><Metric icon={<Activity size={14} />} label="Open issues" value={String(data.repository.openIssues)} detail={data.repository.language || "Language unavailable"} /></div><div className="nexuss-git-analytics-columns"><section><div className="nexuss-git-section-heading"><div><span className="nexuss-git-eyebrow">Developer activity</span><h3>Recent commits</h3></div></div>{data.commits.length ? <div className="nexuss-git-analytics-list">{data.commits.slice(0, 8).map((commit) => <div key={commit.sha || `${commit.author}-${commit.date}`}><GitCommitHorizontal size={13} /><span><strong>{commit.message || "Untitled commit"}</strong><small>{commit.author} · {commit.date ? new Date(commit.date).toLocaleDateString() : "date unavailable"}</small></span></div>)}</div> : <p className="nexuss-git-analytics-muted">No recent commits were returned.</p>}</section><section><div className="nexuss-git-section-heading"><div><span className="nexuss-git-eyebrow">Participation</span><h3>Top contributors</h3></div></div>{data.contributors.length ? <div className="nexuss-git-analytics-list">{data.contributors.slice(0, 8).map((contributor) => <div key={contributor.login}><Users size={13} /><span><strong>{contributor.login}</strong><small>{contributor.contributions} contributions</small></span><em>{contributor.contributions}</em></div>)}</div> : <p className="nexuss-git-analytics-muted">Contributor data is unavailable.</p>}</section></div><p className="nexuss-git-analysis-note">Metrics are derived from bounded GitHub API samples and are intended for workspace orientation, not billing or audit reporting.</p></div>;
}
